p=int(input('enter Physics'))
c=int(input('enter Chenistry'))
m=int(input('enter Math'))
e=int(input('enter English'))
h=int(input('enter Hindi'))
total=p+c+m+e+h
avg=total/5
print('............................................................')
print('                         Marksheet                          ')
print('............................................................')
print('|{:^5s}|{:^20s}|{:^5s}|{:^5s}|{:^5s}|'.format('Sno.','Subject','max','Min','Obj'))
print('|{:^5d}|{:^20s}|{:^5d}|{:^5d}|{:^5d}|'.format(1,'physics',100,33,p))
print('|{:^5d}|{:^20s}|{:^5d}|{:^5d}|{:^5d}|'.format(2,'CHEMISTRY',100,33,c))
print('|{:^5d}|{:^20s}|{:^5d}|{:^5d}|{:^5d}|'.format(3,'MATH',100,33,m))
print('|{:^5d}|{:^20s}|{:^5d}|{:^5d}|{:^5d}|'.format(4,'ENGLISH',100,33,e))
print('|{:^5d}|{:^20s}|{:^5d}|{:^5d}|{:^5d}|'.format(5,'HINDI',100,33,h))
print('............................................................')
print('|{:^5s} {:^20s}|{:^5d}|{:^5d}|{:^5d}|'.format(' ','Total',500,165,total))
print('............................................................')
print('|{:^5s} {:^20s}|{:^5d}|{:^5d}|{:^5.2f}|'.format(' ','Avg',100,33,avg))
print('............................................................')
